### ISSUE TITLE
CLI documentation request (arguments)

### ISSUE THREAD

**Issue by coryhamma** [cetteup/update-plex-ipv6-access-url#2]
I'm using a plex server on my home network. My Internet connection is T-Mobile Home Internet 5G, which uses CG-NAT and does not offer port forwarding. However, it does offer ipv6 and uPnP. Therefore, I plan to use MiniuPnP CLI combined with this script to open the appropriate ipv6 inbound port and update Plex with the right ipv6 address. 

It seems like this script is run with the following arguments:

1. Network port
2. Plex config file (?)

It also seems like you need to have initially entered a custom ipv6 URL in the Plex config.

Please excuse me - I gave it a cursory view but haven't delved deep into the script. Thanks for your efforts in figuring this out!

**Comment by cetteup** [comment]
I actually had to really re-read the script myself to find out what the parameters are, sorry about that. I will add some documentation later, but here's the gist of it:

1. Network interface to use (Plex is listening on)
2. Path to Plex config file

It does not require the port, since never changes and the script would just replace the IP before the colon of any port given as part of the custom connection.

**Comment by raphaelfuchter** [comment]
Hi, where is the Path to Plex config file located in the script? I didn't find to change :(

**Comment by cetteup** [comment]
You don't need to change the script to provide the path to the Plex config file. Instead, provide it as one of the arguments like so:

```bash
./update-plex-ipv6-access-url.sh ens18 "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Preferences.xml"
```
