### ISSUE TITLE
Help on windows

### ISSUE THREAD

**Issue by NiveousSpiritus1** [cetteup/update-plex-ipv6-access-url#7]
Apologies for this, but I was wondering how exactly you make sure this script runs periodically on windows, and also - where do you add in the new arguments to send it to the preferences XML. I'm trying to understand the readme, but I am horribly confused. Sorry.

**Comment by cetteup** [comment]
This script only works on Linux/Unix-based systems. The only way to run it on Windows would be to install the Windows Subsystem for Linux (WSL).

**Comment by cetteup** [comment]
You just gave me an idea though. Give me an hour or two, I might be able to cook something up.

**Comment by cetteup** [comment]
I rewrote the entire project in go, adding lots of features and improvements.

Try downloading the latest [beta release](https://github.com/cetteup/update-plex-ipv6-access-url/releases/tag/v0.1.0-beta.2). The file you probably need is [update-plex-ipv6-access-url-v0.1.0-beta.2-windows-amd64.zip](https://github.com/cetteup/update-plex-ipv6-access-url/releases/download/v0.1.0-beta.2/update-plex-ipv6-access-url-v0.1.0-beta.2-windows-amd64.zip).

Some brief instructions:
1. Download and extract the release .zip file
2. Open a Powershell window
3. Drag and drop `update-plex-ipv6-access-url.exe` into Powershell
4. Hit enter to run the tool
5. When prompted to enter the server address, enter `http://localhost:32400`, if you are running the tool on the same machine as your Plex server (otherwise use `http://[server-ip]:32400`, e.g. `http://192.168.2.100:32400`)
6. Once you entered the server name, hit enter
7. When prompted to enter the network interface name, enter one of the available options in the settings under Network > Preferred network interface (remember: you need to enter the name of the network adapter that has an IPv6 address)
8. 6. Once you entered the network interface name, hit enter
9. Finally, paste/enter a plex token, which you can find by follow [these instructions](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)
10. Press enter once you entered/pasted the token

![2023-04-17_00-04](https://user-images.githubusercontent.com/17167062/232345161-91bb8393-9551-45da-9dff-a982265a1ea3.png)

The tool will automatically detect and configure an IPv6 custom access URL for you. No need to restart the server. You should be able to see the custom access URL appear under Network > Custom server access URLs. If you cannot find that setting, make sure you clicked "Show Advanced" in the top right.

**Comment by NiveousSpiritus1** [comment]
Thank you so much! It works. Apologies for the long wait. Just a question, but is there any way to allow outside internet connections a direct connection? Everything runs perfectly, but now outside internet only receives indirect access. Is this simply due to Ipv6 and outside connections being Ipv4?

**Comment by cetteup** [comment]
Double check your port forwarding/firewall rules. Most routers require you to set up separate rules for IPv4 and IPv6.
